### ISSUE TITLE
`termId` somehow not getting registered?

### ISSUE THREAD

**Issue by quinnj** [felixjung/repl-term#4]
Hey, thanks for the package; I'm just giving Atom a shot and wanted exactly this functionality.

So I can currently run `cmd + alt + L` to launch a Julia repl in terminal, but when I got to `cmd + alt + S` a selection, it just launches a new repl (and `@focusWindow` doesn't seem to work at all for me, I always have to go and hunt down the actual Terminal window).

Looking at the code a bit, it seems like `termId` isn't getting set somehow. I also eventually see the following error when launching a REPL.

<img width="753" alt="screen shot 2015-07-15 at 6 54 41 am" src="https://cloud.githubusercontent.com/assets/2896623/8698835/727c3c82-2abe-11e5-88d8-a2780a4a051f.png">

Any tips? Definitely willing ot help debug this.

Currently running OSX Yosemite 10.10.4

**Comment by felixjung** [comment]
HI @quinnj, Thanks for reporting. Not right now, but I'll take a look this weekend and push a fix.

**Comment by felixjung** [comment]
OK, I got this fixed along with some more bugs coming from API changes in 1.0. Those were unfortunately not reported by the deprecation cop. Please try again with version 0.1.4.

Felix
